#!/bin/bash
#PBS -l nodes=1:ppn=8  		# Requests 1 node and 8 processors per node
#PBS -l walltime=72:00:00 	# Sets max walltime for the job to 48 hours
#PBS -j oe			# Merge output and error files as standard output.

#cd $PBS_O_WORKDIR		# to the directory that you are submitting the job

#ulimit -s unlimited

cd NBO/force

g16 < 10000.gjf | tee force.log 

formchk force.chk


#--------------CHECK-----------------
TailOut=$(tac *.log | grep -m 1 -v '^$' | awk '{print $1}')
[[ "$TailOut" = "Normal" ]] && touch finished || touch terminated
#------------------------------------

cd ../../

